language: node_js

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

os:
  - linux

env:
  - ARCH=x86_64

node_js:
  - '6'
  
before_install:
  - npm i -g yarn

install:
  - yarn

script:
  - yarn lint
    
  
