name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: pip-requirements
      run: pip install -r requirements.txt

    - name: npm-setup
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: npm-install-setup
      uses: bahmutov/npm-install@v1
      with:
        working-directory: ./

    - name: build-docs
      run: ./build-docs-ci.sh

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: minio-docs-artifact
        compression-level: 9
        path: ./minio
