name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: pip-requirements
      run: pip install -r requirements.txt

    - name: npm-setup
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: npm-install-setup
      uses: bahmutov/npm-install@v1
      with:
        working-directory: ./

    - name: build-docs
      run: ./build-docs-ci.sh

    - name: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: assets
        compression-level: 9
        path: ./minio

    - name: Publishing
      uses: burnett01/rsync-deployments@7.0.2
      with:
        path: ./minio/
        switches:  --mkpath -rv --delete
        remote_path: ${{ secrets.DEPLOY_PATH }}/${{ github.event.pull_request.head.ref }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
        remote_key_pass: ${{ secrets.DEPLOY_KEY_PASS }}